zKillboard/zKillboard

themes/base.html

If no text box is currently in focus, pressing forwardslash should set focus to the search box.
This is pretty common among websites (twitter, facebook, github, etc) and helpful for programming nerds.

Added common vim-style search keyboard shortcut.

---

classes/Related.php

This change affects the automatic grouping of involved entities . It will calculate who dislikes who more and try to sort parties accordingly. 
It's of course still not perfect since not all fights only consist of 2 sides, and sometimes it will probably mess up, but I believe it's going to be a noticeable improvement on the current implementation.
On a BR with 194 distinct involved it took circa 0.07s and temporarily raised memory by 0.3MB which went down after the calculation. So in terms of performance hit it will probably not make the page noticeably slower.

Better grouping of entities on the related/BR page

---

classes/Info.php

Because the same field will be queried many many times the additional in-mem caching cuts a lot of the overhead.
Ideally the code should be refactored to not need to call the data so often, but once I found the bottleneck it was fairly easy to introduce this fix, so why not.
For reference, on the bacc event BR the method was called 243,246 times.
After adding the caching it hit the inner part 9,874 times. 
https://zkillboard.com/related/30003792/201512052100/
The fix will do mostly nothing for smaller BR's since there will be very little overlap in characters/ships/etc...

Dirty performance improvement for large related kills pages.

---

public/css/style-edits/cyborg-main.css

up to you if you want this or not. maybe I'm getting old but it's sometimes hard to tell what dropped and didn't with the background and the tinting and the lighting and whatever else.
here's what a random killmail (from latest) would look like with this in:

make the price of dropped items stand out a bit

---

classes/Info.php

I added spacers between the key parameters to prevent unseen duplicates. I looked into the code and saw most spacers you use are : so i sticked to those.
**Example:**
type = 12
id = 34
field = 56 
would generate 123456
type = 123
id = 4
field = 56 
would also generate 123456 but both should return different results

Added spacer between key parameters, to prevent duplicates.

---

view/apistats.php

This should always be an object, even if it's empty.
Old Examples:
`"activepvp":[]`
`"activepvp":{"kills":{"type":"Total Kills","count":6}}`
New Examples:
`"activepvp":{}`
`"activepvp":{"kills":{"type":"Total Kills","count":6}}`
This change casts it to `(object)` in the API view.

Fix the type of "activepvp" in the stats API

---

templates/components/item_list.html

When viewing a killmail, screen sizes smaller than ~767px currently hide the destroyed ship row as well as the "Total Dropped", "Total Destroyed", and "Grand Total" rows. I think this should not occur, as it is useful information that does not negatively impact viewing the site at such a small size.
This pull request removes that CSS class from the affected rows.

remove hidden-xs from dropped/destroyed ship+totals

---

public/js/rankstablesort.js

The most common use case for sorting this column is most likely seeing the most expensive items, not the least. This changes the default sort order from ascending to descending.
My first PR here, apologies if I'm doing something a bit off.
I am slightly concerned that the column is positional and there's no comment about which is the price column, but this doesn't seem to make that any worse.

Set default sort order on item list price column to descending

---

public/css/main.css
templates/detail.html

It is very annoying when you open somewhere linked a killmail on mobile device and cannot open related. So i decided to fix it plus little css tuning for Fitting Panel on xs sizes.
It should be looks like this

show related link in kill details for mobile devices

---

classes/Comments.php

A friend wanted me to ask Squizz if zKB could get a poop emoji because her own friend likes plastering it on wacky killmails in Discord, but Tweetfleet `#zkillboard` said to open a pull request with the change.  Why are we like this?  I don't know.
Serious details: I looked for places the database might need to be updated, but didn't see anything obvious.  As far as I can tell, it really just is adding new ones to the end to not disrupt the existing comment order.

Added Poop Emoji to Comments

---

templates/navigationbar.html

The 10b/ drop down item for the "Menu" in the navigation bar is missing a `/`.

Add trailing slash for 10b nav. item

---

templates/related.html

br.inyour.space doesn't work since disabling startTime/endTime params.
So no sense to hold link to it on Related page.

Related: Removed link to br.inyour.space

---

templates/footer.html

adjust the spelling of `GitHub` in the footer to follow the official spelling with an uppercase `H`.
sorry for opening a PR about that, but I couldn't unsee it again :)

update Github to GitHub in footer

---

templates/footer.html

There's a missing separator between `Legal` and `About`.

nit: Missing separator in the footer menu

---

templates/navigationbar.html

added [recent](https://zkillboard.com/ranks/recent/killers/) and [alltime](https://zkillboard.com/ranks/alltime/killers/) to the navmenu (at the bottom), apparently they've never been there before.

added top10 recent/alltime to nav menu

---

templates/navigationbar.html

The Menu link for `Hourly Stats` does link to `/top/lasthour/w-space/` while it should probably link to `/top/lasthour/all/`.

Hourly Stats automatically goes to w-space

---

templates/navigationbar.html

Using the new advanced search filtering for capitals and structures,
this commit adds easily discoverable entries in the page template
for viewing PVP capital and structure lossmails.
Signed-off-by: Sean Pianka <pianka@eml.cc>

feat: add Menu entries for PVP Capital and Structure mails

---

classes/Trophies.php

Fix for error caused by not adding the filter value to the awox filter when coming from trophies.
Should fix #272 
Alternativly the awox filter needs to be changed to automatically use 1 as filter value.
Fly safe,
nicti

Fix not applied filter for awox link from trophies

---

README.md
templates/footer.html
view/detail.php

Update links and use https for speed and security. Fix some of the typos in the comments for increased readability. Fix div class typo. Update the readme link and use stylized EVE. Choose a better UniWiki link. New request because of lack of git knowledge see #291

  Minor fixes of links and typos

---

view/overview.php

Added error handling in overview.php for `convertUriToParameters` function to avoid displaying plain white error page.
Resolves #297

Catch exception from convertUriToParameters and render proper error page

---

cron/3.queueProcess.nolock.php

Fix for #313
Since I am not sure what the reasoning behind the 0.05 difference was, I am not sure if there are other parts that can break through this, but I was able to verfiy that the labels get assigned correctly after this change.

Fix secStatus class
