zKillboard/zKillboard

- classes/Related.php
Reverts zKillboard/zKillboard#16
> Revert "Better grouping of entities on the related/BR page"

- classes/Related.php
Here's a revert of the revert for the yada yada related pages.
> Reverting fd57797 Revert "Better grouping of entities on the related/BR page"

- public/js/search.js
Maybe needs some event intercepting to not trigger the link in a unwanted way but should work, otherwise ill shoot another PR
> Add real links so opening in new tab works

- classes/Info.php
I don't write much PHP, so this is probably wrong. I was checking how you implemented that function and noticed you used that array and all those array operations on it, but then only returned the itemID value, so here's my take on solving the same problem with possibly a bit less cpu cycles!
I apologize for code style / indentation / etc, didn't check if there was a standard to follow, was just a quick change, feel free to discard it :)
> Rewrote the main cycle in Info::getLocationID

- twig.php
- view/index.php
Removed unused variables
Removed comment since subdomain class is fully removed
Changed static domain to config variable
> Code cleanup

- classes/Api.php
- classes/CrestFittings.php
- classes/CrestSSO.php
- classes/CrestTools.php
- classes/Detail.php
- classes/Disqus.php
- classes/Mdb.php
- classes/MongoFilter.php
- classes/Points.php
- classes/Price.php
- classes/Related.php
- classes/Stats.php
- classes/Trophies.php
- classes/UserGlobals.php
- templates/components/wars_table.html
Fixed html error in wars_table.html
Removed unused code
Added some initial code for previous undeclared variables
> Cleanup code for classes

- templates/overview.html
> Fix issue with wrong tab being highlighted

- tests/view/apistats.php
- view/apistats.php
You can run this test with `phpunit tests/view/apistats.php` using any vaguely recent version of phpunit
> Add a unit test for the stats API fix

- public/css/main.css
- templates/components/tracked_items.html
I feel like this existed before and may therefore have been an intentional change.
It's styling and therefore entirely subjective, but in my humble opinion center alignment looks significantly better than right alignment on this element.
> Centering text on tracked_items td's

- classes/Comments.php
> Add new comment vote thing

- setup/default.config.php
these are the missing config options
> add missing config options

- public/js/zkb-map.js
> make the map great again

- public/css/main.css
- public/js/search.js
> Correct search results placement on mobile screens

- public/js/common.js
> Open notification kills in new tabs

- classes/Comments.php
> Votey thing

- cron/9.queuePublish.php
You should definitely look into getting yourself a zkillboard TLD, though.
> Fix zKillboard URL construction

- classes/Build.php
- cron/9.priceFetcher.php
CCP's adjusted price is terrible for certain items like citadel rigs and can be off by an order of magnitude. (Example: "Standup XL-Set Laboratory Optimization I" is listed as around 3b while the build price is around 40b).
> Don't use adjusted price for buildable items

- classes/Related.php
> Sort by ship mass, then by type ID

- classes/zkbSearch.php
I do NOT have a php environment and DID NOT test this. I literally created this using the Github Editor, please test locally to make sure I got the paths correct..
I was working on Search for my Killboard and while reviewing how you handled it I noticed the outdated paths.
> Update Images used in Search Results

- templates/components/kill_list_row.html
- view/killlistrow.php
Replace sec status with wormhole class on kill list, as per idea in #311
> Wormhole indicator on killlist

- classes/Related.php
- templates/related.html
Draft commit to add collecting and displaying of isk dropped per team.
ToDo:
- Fix wording for ISK lost/ISK dropped to avoid confusion
> ISK Dropped on related

- classes/Related.php
- templates/related.html
Add USD/EUR/GBP to ISK lost and Loot Dropped in related view.
> Add real world prices to ISK Lost, Loot Dropped in related
